BiocManager::install("curatedOvarianData")
library("curatedOvarianData") 
source(system.file("extdata", "patientselection.config", package = "curatedOvarianData"))
set.seed(123)
data("TCGA_eset")
varLabels(TCGA_eset)
mat.gene = exprs(TCGA_eset)
y = mat.gene[1,]
x = t(mat.gene[2:6,])
dd = cbind(y, x)
dd = as.data.frame(na.omit(dd))
head(dd)
tail(dd)
summary(lm(y~A2M+A4GNT+AAAS+AACS+AADAC, data = dd))